name: Vercel Staging Deployment

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches:
      - develop

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-staging:
    name: Deploy to Vercel Staging
    runs-on: ubuntu-latest
    # Only deploy if the CI/CD workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Deploy to Vercel Staging
      id: deploy
      run: |
        echo "🚀 Deploying to Vercel Staging..."
        DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
        echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
        echo "✅ Staging deployment completed: $DEPLOYMENT_URL"
        
        # Optionally set an alias for staging
        vercel alias $DEPLOYMENT_URL sessionforge-staging.vercel.app --token=${{ secrets.VERCEL_TOKEN }} || true
        
  notify-failed-deployment:
    name: Notify Failed Deployment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
    - name: Deployment Blocked
      run: |
        echo "❌ Staging deployment blocked - tests failed!"
        echo "Please check the test results in the CI/CD Pipeline workflow."
        exit 1